version: 1
formatters:
  simple:
    format: '{asctime} - {name} - {levelname} - {message}'
    style: '{'
handlers:
  console:
    # FIXME Executor disturbes uvloop
    #class: debellator.core.ExecutorConsoleHandler
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
loggers:
  debellator:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
